src/Entity/Pages.php
<?php

namespace App\Entity;

use App\Repository\PagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: PagesRepository::class)]
class Pages
{
    #[Groups('main')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[Groups('main')]
    #[ORM\Column(length: 100)]
    private ?string $default_slug = null;

    #[Groups('main')]
    #[ORM\Column()]
    private \DateTimeImmutable $date_created;

    #[Groups('main')]
    #[ORM\Column(type: 'datetime')]
    private ?\DateTime $date_modified = null;

    #[ORM\OneToMany(targetEntity: PageTranslation::class, mappedBy: 'Page', orphanRemoval: true, cascade: ['persist'])]
    private Collection $pageTranslations;

    #[ORM\OneToOne(targetEntity: Menu::class, mappedBy: 'page', cascade: ['persist', 'remove'])]
    private ?Menu $menu = null;

    #[ORM\ManyToMany(targetEntity: Media::class, inversedBy: 'pages')]
    private Collection $media;

    #[ORM\OneToOne(targetEntity: Media::class, inversedBy: 'page', cascade: ['persist', 'remove'])]
    private ?Media $mainPhoto = null;

    public function __construct()
    {
        $this->date_created = new \DateTimeImmutable();
        $this->pageTranslations = new ArrayCollection();
        $this->media = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDefaultSlug(): ?string
    {
        return $this->default_slug;
    }

    public function setDefaultSlug(string $default_slug): self
    {
        $this->default_slug = $default_slug;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function getDateModified(): ?\DateTimeInterface
    {
        return $this->date_modified;
    }

    public function setDateModified(\DateTimeInterface $date_modified): self
    {
        $this->date_modified = $date_modified;

        return $this;
    }

    /**
     * @return Collection|PageTranslation[]
     */
    public function getPageTranslations(): Collection
    {
        return $this->pageTranslations;
    }

    public function addPageTranslation(PageTranslation $pageTranslation): self
    {
        if (!$this->pageTranslations->contains($pageTranslation)) {
            $this->pageTranslations[] = $pageTranslation;
            $pageTranslation->setPage($this);
        }

        return $this;
    }

    public function removePageTranslation(PageTranslation $pageTranslation): self
    {
        if ($this->pageTranslations->removeElement($pageTranslation)) {
            // set the owning side to null (unless already changed)
            if ($pageTranslation->getPage() === $this) {
                $pageTranslation->setPage(null);
            }
        }

        return $this;
    }

   /*  public function __toString(){
        return $this->default_slug;
    } */

   public function getMenu(): ?Menu
   {
       return $this->menu;
   }

   public function setMenu(?Menu $menu): self
   {
       // unset the owning side of the relation if necessary
       if ($menu === null && $this->menu !== null) {
           $this->menu->setPage(null);
       }

       // set the owning side of the relation if necessary
       if ($menu !== null && $menu->getPage() !== $this) {
           $menu->setPage($this);
       }

       $this->menu = $menu;

       return $this;
   }

   public function __toString()
   {
       return $this->title;
   }

   /**
    * @return Collection|Media[]
    */
   public function getMedia(): Collection
   {
       return $this->media;
   }

   public function addMedium(Media $medium): self
   {
       if (!$this->media->contains($medium)) {
           $this->media[] = $medium;
       }

       return $this;
   }

   public function removeMedium(Media $medium): self
   {
       $this->media->removeElement($medium);

       return $this;
   }

   public function getMainPhoto(): ?Media
   {
       return $this->mainPhoto;
   }

   public function setMainPhoto(?Media $mainPhoto): self
   {
       $this->mainPhoto = $mainPhoto;

       return $this;
   }
}

src/Controller/pdfController.php
<?php

namespace App\Controller;

use App\Entity\Invoices;
use App\Entity\Reservation;
use App\Repository\DatesRepository;
use App\Repository\InvoicesRepository;
use App\Repository\UserRepository;
use App\Service\pdfHelper;
use App\Service\UploadHelper;
use Doctrine\ORM\EntityManagerInterface;
use Mpdf\Mpdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class pdfController extends AbstractController
{
    private $mpdf;

    public function __construct(Mpdf $mpdf)
    {
        $this->mpdf = $mpdf;
    }

    #[Route(path: '/makepdf/', name: 'makepdf')]
    public function index(
        DatesRepository $datesRepository,
        UserRepository $userRepository,
        InvoicesRepository $invoicesRepository,
        EntityManagerInterface $em,
        Environment $twig,
        UploadHelper $uploadHelper,
        pdfHelper $pdfHelper,
        $locale = 'es'): Response
    {
        $reservation = new Reservation();
        $date = $datesRepository->find(60);
        $user = $userRepository->find(1877);
        $reservation->setDate($date);
        $reservation->setUser($user);
        $reservation->setNbpilotes(2);
        $reservation->setNbAccomp(3);

        $invoice = new Invoices();
        $invoice->setReservation($reservation);
        $invoice->setName('XXXX XXX');
        $invoice->setNif('0000000X');
        $invoice->setAddress('c. xxxxx 00');
        $invoice->setPostalCode('00000');
        $invoice->setCity('XXXXXXX');
        $invoice->setCountry('XX');
        $invoice->setInvoiceNumber('00000');

        $file = $pdfHelper->storeInvoicePdf($invoice, $locale, count($invoicesRepository->findAll()));

        $em->persist($invoice);
        $em->flush();

        return new Response('uploaded');
    }
}

templates/pdf/pdf_content.html.twig
{% set total = 0 %}
{% set discount = 0 %}
{% set prixPilote = invoice.reservation.date.prixPilote %}
{% set prixAccomp = invoice.reservation.date.prixAccomp %}
{% if statusChange is defined and statusChange == 'cancelled' %}
    {% set prixPilote = prixPilote|negativify %}
    {% set prixAccomp = prixAccomp|negativify %}
{% endif %}

{% set totalPilote = invoice.reservation.nbpilotes * prixPilote %}
{% set totalAccomp = invoice.reservation.nbaccomp * prixAccomp %}
{% set total = totalPilote + totalAccomp %}

<br />
    <div id="details" class="clearfix">
        <div id="client" class="clearfix">
            <div class="to">{{ 'CLIENTE'|trans }}:</div>
                <h2 class="name">{{ invoice.name }}</h2>
                <div class="address">
                    {{ invoice.address }}<br />
                    {{ invoice.city }}<br />
                    {{ invoice.postalcode }}<br />
                    {{ invoice.country }}
                </div>
                <br />
                <div class="idcard">{{invoice.nif}}</div>
                {# <div class="email"><a href="mailto:john@example.com">{{invoice.country}}</a></div> #}
            </div>
            <div id="invoice">
                <h1>{{'FACTURA'|trans}}</h1>
                <div class="invoiceNumber">{{'Número de factura'|trans}}: {{ invoice.invoiceNumber }}</div>
                <div class="date">{{'Fecha de factura'|trans}}: {{ invoice.dateCreated|date('Y/m/d') }}</div>
                <div class="date">{{'Fecha de vencimiento'|trans}}: {{'1 mes antes de la salida del viaje' |trans}}</div>
            </div>
        </div>
        <table border="0" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th class="no">{{'CONCEPTO'|trans}}</th>
                    <th class="desc">{{'DESCRIPCIÓN'|trans}}</th>
                    <th class="unit">{{'PRECIO'|trans}}</th>
                    <th class="qty">{{'CANTIDAD'|trans}}</th>
                    <th class="total">{{'TOTAL'|trans}}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>{{'Viaje'|trans}}</strong></td>
                    <td>{{ renderLocalizedCategory(invoice.reservation.date.travel.category.id, locale)}}</td>
                    <td colspan="3">
                        {{ renderLocalizedTravel(invoice.reservation.date.travel.id, locale) }}
                    </td>


                </tr>
                <tr>
                    <td colspan="5">{{'Código de reserva'|trans}}: {{ invoice.reservation.code }}</td>
                </tr>
                {% if invoice.reservation.nbpilotes > 0 %}
                    <tr>
                        <td><strong>{{'Nº de pilotos'|trans}}</strong></td>
                        <td></td>
                        <td>{{ prixPilote | format_currency('EUR', {fraction_digit: 2}) }}</td>
                        <td>{{ invoice.reservation.nbpilotes }}</td>
                        <td>{{ totalPilote | format_currency('EUR', {fraction_digit: 2}) }}
                        </td>
                    </tr>
                {% endif %}
                {% if invoice.reservation.nbaccomp > 0 %}
                <tr>
                    <td><strong>{{'Nº de acompañantes'|trans}}</strong></td>
                    <td></td>
                    <td>{{ prixAccomp | format_currency('EUR', {fraction_digit: 2}) }}</td>
                    <td>{{ invoice.reservation.nbaccomp }}</td>
                    <td>{{ totalAccomp | format_currency('EUR', {fraction_digit: 2}) }}</td>
                </tr>
                {% endif %}
                {% if invoice.reservation.reservationOptions|length > 0 %}
                <tr>
                    <td><strong>{{'Opciones'|trans}}</strong></td>
                    <td colspan="4">
                    <table>
                        {% for reservationOption in invoice.reservation.reservationOptions %}
                            <tr>
                                <td>
                                    <strong>{{reservationOption.ammount}}x</strong>
                                </td>
                                <td>
                                    {{ renderLocalizedOption(reservationOption.option.id, locale) }}
                                </td>
                                <td>
                                    {% set optionPrice = reservationOption.option.price %}
                                    {% if statusChange is defined and statusChange == 'cancelled' %}
                                        {% set optionPrice = reservationOption.option.price|negativify %}
                                    {% endif %}
                                    {{ optionPrice | format_currency('EUR', {fraction_digit: 2}) }}
                                </td>
                                <td>

                                    {{ (reservationOption.ammount * optionPrice) | format_currency('EUR', {fraction_digit: 2}) }}

                                    {% set total = total + reservationOption.ammount * optionPrice %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    </td>
                </tr>
                {% endif %}

                {% if invoice.reservation.codespromo is defined and invoice.reservation.codespromo != null %}
                    <tr>
                        <th>{{ 'Bono descuento'|trans}}</th>
                        <td>{{ invoice.reservation.codespromo.code }}</td>
                        <td>{{ invoice.reservation.codespromo.commentaire}}</td>
                        <td>
                        {% if invoice.reservation.codespromo.montant != 0 %}
                            - {{ invoice.reservation.codespromo.montant|format_currency('EUR', {fraction_digit: 2}, locale=app.request.getLocale() ) }}
                            {% set discount = discount + invoice.reservation.codespromo.montant %}
                        {% elseif invoice.reservation.codespromo.pourcentage != 0 %}
                            - {{ invoice.reservation.codespromo.pourcentage }} %
                            {% set discount = total * invoice.reservation.codespromo.pourcentage / 100 %}
                        {% endif %}
                        </td>
                        <td align="right">
                            {{discount | format_currency('EUR', {fraction_digit: 2})}}
                        </td>
                    </tr>

				{% endif %}
                {% set total = total - discount %}
                <tr>
                    <td colspan="4"><strong>{{'Base'|trans}}</strong></td>
                    <td>{{ (total/1.21) | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                <tr>
                    <td colspan="4"><strong>{{'IVA'|trans}} (21%)</strong></td>
                    <td>{{ (total*(1-1/1.21)) | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                <tr>
                    <td colspan="4"><strong>{{'Total'|trans}}</strong></td>
                    <td>{{ total | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                {% if invoice.reservation.status == "cancelled" %}
                    <tr>
                        <td colspan="4"><strong>{{'Valor de cancelación'|trans}}</strong></td>
                        <td>- {{ total | format_currency('EUR', {fraction_digit: 2})}} </td>
                    </tr>
                    <tr>
                        <td colspan="4"><strong>{{'Total a pagar'|trans}}</strong></td>
                        <td> {{ 0 | format_currency('EUR', {fraction_digit: 2})}} </td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <div id="thanks">{{'¡Muchas gracias!'|trans}}</div>

templates/pdf/pdf_content_manual.html.twig
{# {% set total = 0 %}
{% set discount = 0 %}
{% set prixPilote = invoice.reservation.date.prixPilote %}
{% set prixAccomp = invoice.reservation.date.prixAccomp %}
{% if statusChange is defined and statusChange == 'cancelled' %}
    {% set prixPilote = prixPilote|negativify %}
    {% set prixAccomp = prixAccomp|negativify %}
{% endif %}

{% set totalPilote = invoice.reservation.nbpilotes * prixPilote %}
{% set totalAccomp = invoice.reservation.nbaccomp * prixAccomp %}
{% set total = totalPilote + totalAccomp %} #}

<br />
    <div id="details" class="clearfix">
        <div id="client" class="clearfix">
            <div class="to">{{ 'CLIENTE'|trans }}:</div>
                <h2 class="name">{{ invoice.name }}</h2>
                <div class="address">{{invoice.address}}, {{invoice.city}} {{invoice.postalcode}}, {{invoice.country}}</div>
                <br />
                <div class="idcard">{{invoice.nif}}</div>
                {# <div class="email"><a href="mailto:john@example.com">{{invoice.country}}</a></div> #}
            </div>
            <div id="invoice">
                <h1>{{'FACTURA'|trans}}</h1>
                <div class="invoiceNumber">{{'Número de factura'|trans}}: {{ invoice.invoiceNumber }}</div>
                <div class="date">{{'Fecha de factura'|trans}}: {{ invoice.dateCreated|date('Y/m/d') }}</div>
                <div class="date">{{'Fecha de vencimiento'|trans}}: {{'1 mes antes de la salida del viaje' |trans}}</div>
            </div>
        </div>
        <table border="0" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th class="no">{{'CONCEPTO'|trans}}</th>
                    <th class="desc">{{'DESCRIPCIÓN'|trans}}</th>
                    <th class="unit">{{'PRECIO'|trans}}</th>
                    <th class="qty">{{'CANTIDAD'|trans}}</th>
                    <th class="total">{{'TOTAL'|trans}}</th>
                </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>{{'Description'|trans}}</strong></td>
                <td colspan="4">{{invoice.description}}</td>
              </tr>
                {# <tr>
                    <td><strong>{{'Viaje'|trans}}</strong></td>
                    <td>{{ renderLocalizedCategory(invoice.reservation.date.travel.category.id, locale)}}</td> #}
                    {# <td colspan="3">
                        {{ renderLocalizedTravel(invoice.reservation.date.travel.id, locale) }}
                    </td>
                </tr>#}
                {#<tr>
                     <td colspan="5">{{'Código de reserva'|trans}}: {{ invoice.reservation.code }}</td>
                </tr>#}
                {# {% if invoice.reservation.nbpilotes > 0 %}
                    <tr>
                        <td><strong>{{'Nº de pilotos'|trans}}</strong></td>
                        <td></td>
                        <td>{{ prixPilote | format_currency('EUR', {fraction_digit: 2}) }}</td>
                        <td>{{ invoice.reservation.nbpilotes }}</td>
                        <td>{{ totalPilote | format_currency('EUR', {fraction_digit: 2}) }}
                        </td>
                    </tr>
                {% endif %} #}
                {# {% if invoice.reservation.nbaccomp > 0 %}
                  <tr>
                    <td><strong>{{'Nº de acompañantes'|trans}}</strong></td>
                    <td></td>
                    <td>{{ prixAccomp | format_currency('EUR', {fraction_digit: 2}) }}</td>
                    <td>{{ invoice.reservation.nbaccomp }}</td>
                    <td>{{ totalAccomp | format_currency('EUR', {fraction_digit: 2}) }}</td>
                  </tr>
                {% endif %} #}
                {# {% if invoice.reservation.reservationOptions|length > 0 %}
                  <tr>
                    <td><strong>{{'Opciones'|trans}}</strong></td>
                    <td colspan="4">
                    <table>
                      {% for reservationOption in invoice.reservation.reservationOptions %}
                        <tr>
                          <td>
                            <strong>{{reservationOption.ammount}}x</strong>
                          </td>
                          <td>
                            {{ renderLocalizedOption(reservationOption.option.id, locale) }}
                          </td>
                          <td>
                            {% set optionPrice = reservationOption.option.price %}
                            {% if statusChange is defined and statusChange == 'cancelled' %}
                              {% set optionPrice = reservationOption.option.price|negativify %}
                            {% endif %}
                            {{ optionPrice | format_currency('EUR', {fraction_digit: 2}) }}
                          </td>
                          <td>
                            {{ (reservationOption.ammount * optionPrice) | format_currency('EUR', {fraction_digit: 2}) }}
                            {% set total = total + reservationOption.ammount * optionPrice %}
                          </td>
                        </tr>
                      {% endfor %}
                    </table>
                    </td>
                  </tr>
                {% endif %} #}

                {# {% if invoice.reservation.codespromo is defined and invoice.reservation.codespromo != null %}
                    <tr>
                        <th>{{ 'Bono descuento'|trans}}</th>
                        <td>{{ invoice.reservation.codespromo.code }}</td>
                        <td>{{ invoice.reservation.codespromo.libelle}}</td>
                        <td>{{ invoice.reservation.codespromo.commentaire}}</td>
                        <td align="right">{{ invoice.reservation.codespromo.montant|format_currency('EUR', {fraction_digit: 2}, locale=app.request.getLocale() ) }}</td>
                    </tr>
                    {% set discount = discount + invoice.reservation.codespromo.montant %}
				        {% endif %} #}
                {# {% set total = total - discount %} #}
                <tr>
                    <td colspan="4"><strong>{{'Base'|trans}}</strong></td>
                    <td>{{ (invoice.dueAmmount/1.21) | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                <tr>
                    <td colspan="4"><strong>{{'IVA'|trans}} (21%)</strong></td>
                    <td>{{ (invoice.dueAmmount*(1-1/1.21)) | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                <tr>
                    <td colspan="4"><strong>{{'Total'|trans}}</strong></td>
                    <td>{{ invoice.dueAmmount | format_currency('EUR', {fraction_digit: 2})}} </td>
                </tr>
                {# {% if invoice.reservation.status == "cancelled" %}
                    <tr>
                        <td colspan="4"><strong>{{'Valor de cancelación'|trans}}</strong></td>
                        <td>- {{ total | format_currency('EUR', {fraction_digit: 2})}} </td>
                    </tr>
                    <tr>
                        <td colspan="4"><strong>{{'Total a pagar'|trans}}</strong></td>
                        <td> {{ 0 | format_currency('EUR', {fraction_digit: 2})}} </td>
                    </tr>
                {% endif %} #}
            </tbody>
        </table>
        <div id="thanks">{{'¡Muchas gracias!'|trans}}</div>

templates/pdf/pdf_footer.html.twig
    </main>
    <footer>
      {{ 'Factura válida creada electrónicamente'|trans }}.
    </footer>
  </body>
</html>

templates/pdf/pdf_header.html.twig
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
    </head>
    <body>
        {# <div class="container"> #}
            <header class="clearfix">
                <div id="logo">
                    <img width="220" height="60" src="{{path~(asset('images/rakatanga-tour.png'))}}">
                </div>
                <div id="company">
                    <h2 class="name">RAKATANGA TOUR</h2>
                    <div>C/ Altamira 11. 36002, Pontevedra</div>
                    <div>CIF: B-37569829</div>
                    <div><a href="mailto:company@example.com">info@rakatanga-tour.com</a></div>
                </div>
                <div class="clearfix"></div>
            </header>
            <main>